#!/bin/bash

out="$(wget -q --show-progress -nv -O - https://www.dizionario-latino.com/dizionario-latino-italiano.php?lemma=$1)"
echo "$out" | grep -m 1 paradigma | w3m -dump -T text/html
echo ""

exit
