dict = {
    "abduco": "-is, abduxi, abductum, ĕre",
    "accurro": "-is, accurri, ursum, ĕre",
    "adiuvo": "-as, iuvi, iutum, are",
    "aedifico": "-as, aedificāvi, aedificātum, aedificāre",
    "agito": "-as, agitāvi, agitātum, agitāre",
    "ambŭlo": "-as, ambulāvi, ambulātum, ambulāre",
    "amitto": "-is, amisi, amissum, amittĕre",
    "amo": "-as, amavi, amatum, amare",
    "appārĕo": "-es, apparui, apparitus, apparēre",
    "apprehendo": "-is, prendi, prensum, prendĕre",
    "apto": "-as, aptavi, aptatum, aptare",
    "aro": "-as, aravi, aratum, arare",
    "ascendo": "-is, ascendi, ascensum, ascendĕre",
    "audio": "-is, audi, audīctum, audīre",
    "cado": "-is, cecĭdi",
    "caedo": "-is, cecidi, caesum, ĕre",
    "cano": "- is, cecĭni, cantum, canĕre",
    "canto": "-as, cantāvi, cantātum, cantāre",
    "capio": "-is, cepi, captum, capĕre",
    "celebro": "-as, celebrāvi, celebrātum, celebrāre",
    "circumndo": "-as, curcumdĕdi, circumdătum, circumdăre",
    "clāmo": "-as, clamāvi, clamātum, clamāre",
    "claudo": "-is, clausi, clausum, claudĕre",
    "coepio": "-is, coepi, coeptum, ĕre",
    "cŏlo": "-is, colŭi, cultum, colĕre",
    "comparo": "-as, avi, atum, are",
    "consido": "-is, consedi, conssessum, consedĕre",
    "debello": "-as, avi, atum, are",
    "dēfendo": "-is, defendi, defensum, defendĕre",
    "dēsīdĕro": "-as, desiderāvi, desiderātum, desiderāre",
    "detergo": "-is, texi, tectum, ĕre",
    "dico": "-is, dixi, dictum, dicěre",
    "disco": "-is, didici, discěre",
    "dissuadeo": "-es, suasi, suasum, ēre",
    "docĕo": "-es, dŏcŭi, doctum, docēre",
    "do": "-das, dedi, datum, dare",
    "doleo": "-es, dolŭi, dolĭtūrus, dolēre",
    "dono": "-as, donavi, donatum, donare",
    "dormio": "-is, dormii, dormitum, dormire",
    "effŭndo": "-is, effūsum, effundĕre",
    "emitto": "-is, emisi, emissum, emittĕre",
    "erro": "-as, errāvi, errātum, errāre",
    "erudio": "-is, i",
    "excito": "-as, avi, atum, are",
    "exclāmo": "-as, exclamāvi, exclamātum, exclamāre",
    "fugo": "-as, fugāvi, fugātum, fugāre",
    "gero": "-is, gessi, gestum, ĕre",
    "grăvo": "-as, gravāvi, gravātum, gravāre",
    "habeo": "-es, habui, habēre",
    "hăbĭto": "-as, habitāvi, habitātum, habitāre",
    "haurio": "-is, hausi, haustum, haustīre",
    "honoro": "-as, honorabi, honorātum, honorāre",
    "ignoro": "-as, avi, atum, are",
    "illumino": "-as, illumināvi, illuminātum, illumināre",
    "illustro": "-as, illustrāvi, illustrātum, illulstrāre",
    "immolo": "-as, immolāvi, immolātum, immolāre",
    "implĕo": "-es, implevi, implenum, implēre",
    "imploro": "-as, avi, atum, are",
    "indico": "-is, indixi, indictum, ĕre",
    "inquam": "-inquis, inquit, inquĭi",
    "intro": "-as, intrāvi, intrātum, intrāre",
    "invado": "-is, invasi, invasum, invadere",
    "invenio": "-is, invēni, inventum, invenīre",
    "lateo": "-es, ui, ēre",
    "lavo": "-as, lavi, lavatum, lavare",
    "lego": "-is, legi, lectum, legěre",
    "libero": "-as, liberāvi, liberātum, liberāre",
    "lībĕro": "-as, liberāvi, liberātum, liberāre",
    "ludo": "-is, lusi, lusum, ĕre",
    "manduco": "-as, manducāvi, manducātum, manducāre",
    "maneo": "-es, mansi, mansum, manēre",
    "mico": "-as, mĭcŭi, micāre",
    "misso": "-is, misi, missum, mittĕre",
    "mitto": "-is, misi, missum, mittĕre",
    "moneo": "-es, monui, monitum, monēre",
    "monstro": "-as, monstrāvi, monstrātum, monstrāre",
    "mordeo": "-es, momordi, morsum, mordēre",
    "moveo": "-es, movi, motum, ēre",
    "narro": "-as, narrāvi, narrātum, narrāre",
    "neco": "-as, necāvi, necātum, necāre",
    "nego": "-as, avi, atum, are",
    "nĭtĕo": "-es, nitŭi, nitēre",
    "oboedio": "-is, oboedīvi, oboedītum, oboedīre",
    "obrŭo": "-is, obrui, obrŭtum, obrĕre",
    "occido": "-is, occīdi, occīsum, occidĕre",
    "occupo": "-as, occupāvi, occupātum, occupāre",
    "offendo": "-as, offendi, offensum, offendĕre",
    "oppugno": "-as, avi, atum, are",
    "orno": "-as, ornāvi, ornātum, ornāre",
    "oro": "-as, avi, atum, are",
    "ostendo": "-is, ostendi, ostentum, ĕre",
    "paro": "-as, parāvi, parātum, parāre",
    "pello": "-is, pĕputi, pulsum, pellĕre",
    "pervenio": "-is, ivi, itum, ire",
    "peto": "-is, petivi, petitum, petĕre",
    "pono": "-is, posui, positum, ĕre",
    "porto": "-as, portāvi, portātum, portāre",
    "possideo": "-es, possedi, possessum, possedēre",
    "praebĕo": "-es, praebŭi, praebĭtum, praebēre",
    "proflig": "-is, proflictum, profligĕre",
    "propono": "-is, proposui, propositum, ĕre",
    "pugno": "-as, pugnāvi, pugnātum, pugnāre",
    "puto": "-as, putāvi, putātum, putāre",
    "quiesco": "-is, quĭēvi, quĭētum, quietĕre",
    "rapio": "-is, rapui, raptum, ĕre",
    "rĕcĕo": "-as, recreāvi, recreātum, recreāre",
    "recito": "-as, recitāvi, recitātum, recitāre",
    "rego": "-is, rexi, rectum, ĕre",
    "respondeo": "-es, respondi, responsum, respondere",
    "reverto": "-is, verti, versum, ĕre",
    "rideo": "-es, risi, risum, ridēre",
    "rodo": "-is, rosi, rosum, ĕre",
    "rogo": "-as, avi, atum, are",
    "rudo": "- is, ivi, itum, ire",
    "saluto": "-as, salutāvi, salutātum, salutāre",
    "salveo": "-es, salvēre",
    "seco": "-as, secui, sectum, secāre",
    "sedeo": "-es, sedi, sessum, sedēre",
    "sentio": "-is, sensi, sensum, sentire",
    "servo": "-as, servāvi, servātum, servāre",
    "significo": "-as, significāvi, significātum, significāre",
    "solvo": "-is, solvi, solutum, solĕre",
    "splendēo": "-es, splendēre",
    "statuo": "-is, statui, statutum, ĕre",
    "sum": "-es, fui, esse",
    "surgo": "-is, surrexi, surrectum, surgere",
    "taceo": "-es, tăcŭi, tăcitŭm, tacēre",
    "tempto": "-as, avi, atum, are",
    "terrěo": "-es, terrŭi, territum, terrēre",
    "tolero": "-as, avi, atum, are",
    "torrĕo": "-es, torrŭi, tostum, torrēre",
    "transfigo": "-is, transfixi, transfixum, transfigĕre",
    "vasto": "-as, vastāvi, vastātum, vastāre",
    "veho": "-is, vexi, vectum, ĕre",
    "venero": "-as, avi, atum, are",
    "vĕnĭo": "-is, vēni, ventum, venīre",
    "vergo": "-is, vergĕre",
    "vexo": "-as, vexāvi, vexātum, vexāre",
    "vĭdeo": "-es, vidi, visum, vidēre",
    "vincio": "-is, vinxi, vinctum, vincire",
    "visito": "-as, visitāvi, visitātum, visitāre",
    "vitĭo": "-as, vitāvi, vitātum, vitāre",
    "vito": "-as, vitāvi, vitātum, vitāre",
    "voco": "-as, vocāvi, vocātum, vocāre",
    "volo": "-as, volāvi, volātum, volāre",
    "voro": "-as, vorāvi, vorātum, vorāre",
    "vulnĕro": "-as, vulnerāvi, vulnerātum, vulnerāre",
    "adscisco": "-is, adscivi, adscitum, adsciscere"
}
